### ISSUE TITLE
Webseite lädt sehr langsam

### ISSUE THREAD

**Issue by dickshaydle** [HashTec-Potsdam/wer-ist-da#9]
Bei mir dauert es von zu hause aus über 2 min bis die Seite [freiland.ffp.quelltext.eu] angezeigt wird. Das übrigens nicht nur beim ersten sondern jedes mal.

http://freiland.ffp.quelltext.eu/static/index.css ist sofort da.

**Comment by niccokunzmann** [comment]
Die Seite versucht das hier zu laden: http://10.22.194.208:8080/generated/local-link.css?ip=10.22.194.208,
um festzustellen, ob du auch aus dem Freifunk direkt die Seite erreichen kannst. 
Manchmal werden Seiten nicht angezeigt, wenn sie nicht vollständig geladen sind.
Welchen Web-Browser verwendest du?
Lädt dieser Link auch langsam?

**Comment by dickshaydle** [comment]
Der Link ist gar nicht zu erreichen.
Ich benutze Chromium. Unter firefox muss man übrigens auch warten.
Was ist der Nutzen von dieser Seite?

Was ich verdächtig finde ist zu einen die IP adresse 10.x.x.x . Das ist doch eine lokale Adresse (https://en.wikipedia.org/wiki/Private_network) d.h. die kann doch nur im Netz erreichbar sein. Zum anderen finde ich eigenartig dass die seite ein .css file ist. Hätte da eher .php .html oder so erwartet. Ich dachte, dass css statisch ist und nur die formatierung/style enthält.

**Comment by niccokunzmann** [comment]
> Unter firefox muss man übrigens auch warten.

Ja, die Webseite lädt noch und ist auch zu sehen. - zumindest für mich im Firefox.
Im Chromium sieht man nichts?

10.x.x.x ist lokal. Das ist die Adresse des Raspis, auf dem die Webseite läuft. Wenn man im selben Netz ist, wie die Webseite, wird durch CSS der Link zum Eintragen angezeigt. Ich wollte kein JavaScript und keine IFrames. Man kann das sicher noch verbessern. Aber so braucht es auch kein JavaScript.

**Comment by dickshaydle** [comment]
Wie gesagt die Seite kann ich öffnen aber erst nach 2min. Das sowohl im Chromium als auch im Firefox.

Die Seite soll doch von außerhalb sichbar sein oder nicht. Weshalb dann die css lokal?
Sauberer fänd ichs wenn _bottle_ die html verändert und den Teil der intern bleiben soll nur dann anzeigt.
Ich habs nicht getestet aber es sollte mit ´client_ip = request.environ.get('REMOTE_ADDR')´ gehen.

[how-to-get-client-ip-address-using-python-bottle-framework](https://stackoverflow.com/questions/31405812/how-to-get-client-ip-address-using-python-bottle-framework)

**Comment by niccokunzmann** [comment]
Ja, `client_ip = request.environ.get('REMOTE_ADDR')` nutze ich. Ich müsste aber eine lokale Domainauflösung machen. Dazu brauche Zugriff auf den Router. Diesen habe ich nicht.
Ich kann deinen Fehler leider nicht reproduzieren. Bei mir zu Hause und auch im freiLand lädt es und zeigt sich an.

Mit Firefox kannst du die Webkonsole öffnen Strg+Shift+k. Dort gibt es ein Tab "Netzwerk". Wie sieht das aus?

Sobald ich an einem anderen Standort bin, teste ich das nochmal.

**Comment by niccokunzmann** [comment]
Zur Info: die HTTP-Request an freiland.ffp.quelltext.eu geht diesen Weg:

Du -> Router -> Internet -> mein Router -> mein Server -> Nginx -> Freifunk-Router -> PotsdamVPN -> Freifunk-Router -> Raspi im lokalen Netz

Aus dem Freifunk ganz genauso.

Um herauszufinden, ob der andere aber gleich neben der Webseite im selben Netz sitzt, gibt es eine Anfrage an die lokale IP.

**Comment by niccokunzmann** [comment]
Ich belese mich am: https://varvy.com/pagespeed/render-blocking-css.html

**Comment by niccokunzmann** [comment]
Ich habe die beiden deployed. Du kannst mal testen, ob es einen Unterschied macht.

**Comment by dickshaydle** [comment]
Ja, die Seite wird jetzt sofort angezeigt und ist aktuell, d.h. der Zeitcounter verändert sich.
Sie wird noch weiter geladen, d.h. ist dann auch erst nach einer längeren Zeit fertig damit, was aber nicht weiter störend ist.

**Comment by niccokunzmann** [comment]
Danke! Ich schließe das dann mal.. Wenn du magst: Heute in der machBar 14:00 Uhr Schokoladengießen.
